=== uo288595/MotoGP/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.uniovi.es"
	xmlns="http://www.uniovi.es"
	elementFormDefault="qualified">

	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombre" />
				<xs:element ref="longitudCircuito" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="horaEsp" />
				<xs:element ref="numeroVueltas" />
				<xs:element ref="localidadProxima" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referenciaBibliografia" />
				<xs:element ref="galeriaFotografia" />
				<xs:element ref="galeriaVideos" />
				<xs:element ref="origenCircuito" />
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="puntoTramo" />
				<xs:element ref="vencedorYTiempo" />
				<xs:element ref="clasificados" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombre" type="xs:string" />
	<xs:element name="longitudCircuito">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoLongitudCircuitoValor">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoLongitudCircuitoValor">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="20000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="tipoAnchuraValor">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="tipoAnchuraValor">
		<xs:restriction base="xs:nonNegativeInteger">
			<xs:minInclusive value="0"/>
			<xs:maxInclusive value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="fecha" type="xs:date" />
	<xs:element name="horaEsp" type="xs:time" />
	<xs:element name="numeroVueltas" type="xs:nonNegativeInteger" />
	<xs:element name="localidadProxima" type="xs:string" />
	<xs:element name="pais" type="xs:string" />
	<xs:element name="patrocinador" type="xs:string" />
	<xs:element name="referenciaBibliografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia" type="xs:string" />
	<xs:element name="galeriaFotografia">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="fotografia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="fotografia" type="xs:string" />
	<xs:element name="galeriaVideos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video" type="xs:string" />
	<xs:element name="origenCircuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenada" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="puntoTramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="distanciaTramo" />
				<xs:element ref="coordenada" />
				<xs:element ref="numeroSector" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="distanciaTramo">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:nonNegativeInteger">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="numeroSector" type="xs:integer" />
	<xs:element name="vencedorYTiempo" type="xs:string" />
	<xs:element name="clasificados">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="piloto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="piloto" type="xs:string" />
	<xs:element name="coordenada">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud">
    <xs:simpleType>
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="-180"/>
            <xs:maxInclusive value="180"/>
        </xs:restriction>
    </xs:simpleType>
	</xs:element>
	<xs:element name="latitud">
    <xs:simpleType>
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="-90"/>
            <xs:maxInclusive value="90"/>
        </xs:restriction>
    </xs:simpleType>
	</xs:element>
	<xs:element name="altitud">
    <xs:simpleType>
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="5000"/>
        </xs:restriction>
    </xs:simpleType>
	</xs:element>
</xs:schema>

=== uo288595/MotoGP/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns="http://www.uniovi.es"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    <nombre>Circuit Ricardo Tormo</nombre>
    <longitudCircuito unidades="metros">4005</longitudCircuito>
    <anchura unidades="metros">12</anchura>
    <fecha>2025-11-16</fecha>
    <horaEsp>14:00:00</horaEsp>
    <numeroVueltas>27</numeroVueltas>
    <localidadProxima>Cheste</localidadProxima>
    <pais>España</pais>
    <patrocinador>Motul</patrocinador>
    <referenciaBibliografia>
        <referencia>https://www.circuitricardotormo.com/sabias-todos-estos-datos-sobre-el-valenciagp-y-el-circuit-ricardo-tormo/</referencia>
        <referencia>https://es.wikipedia.org/wiki/Circuito_Ricardo_Tormo</referencia>
        <referencia>https://www.dazn.com/es-ES/news/motor/gp-valencia-motogp-circuito-ricardo-tormo-cheste-fecha-hora-canal-tv-donde-ver-online-gran-premio-mundial-motociclismo/m8hhcx6f9sgv1d0dfae2gu1qa</referencia>
    </referenciaBibliografia>
    <galeriaFotografia>
        <fotografia>../multimedia/ricardo-tormo.jpg</fotografia>
    </galeriaFotografia>
    <galeriaVideos>
        <video>../multimedia/ricardo-tormo.mp4</video>
    </galeriaVideos>
    <origenCircuito>
        <coordenada>
            <longitud>-0.631082</longitud>
            <latitud>39.483571</latitud>
            <altitud>153</altitud>
        </coordenada>
    </origenCircuito>
    <!-- Sector 1 -->
    <puntoTramo>
        <distanciaTramo unidades="metros">492</distanciaTramo>
        <coordenada>
            <longitud>-0.626336</longitud>
            <latitud>39.486088</latitud>
            <altitud>145</altitud>
        </coordenada>
        <numeroSector>1</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">34</distanciaTramo>
        <coordenada>
            <longitud>-0.626125</longitud>
            <latitud>39.486340</latitud>
            <altitud>145</altitud>
        </coordenada>
        <numeroSector>1</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">33</distanciaTramo>
        <coordenada>
            <longitud>-0.626043</longitud>
            <latitud>39.486651</latitud>
            <altitud>146</altitud>
        </coordenada>
        <numeroSector>1</numeroSector>
    </puntoTramo>
    <!-- Sector 2 -->
    <puntoTramo>
        <distanciaTramo unidades="metros">330</distanciaTramo>
        <coordenada>
            <longitud>-0.627513</longitud>
            <latitud>39.489409</latitud>
            <altitud>150</altitud>
        </coordenada>
        <numeroSector>2</numeroSector>
    </puntoTramo>
    <!-- Sector 3 -->
    <puntoTramo>
        <distanciaTramo unidades="metros">24</distanciaTramo>
        <coordenada>
            <longitud>-0.627782</longitud>
            <latitud>39.489455</latitud>
            <altitud>150</altitud>
        </coordenada>
        <numeroSector>3</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">25</distanciaTramo>
        <coordenada>
            <longitud>-0.628018</longitud>
            <latitud>39.489325</latitud>
            <altitud>150</altitud>
        </coordenada>
        <numeroSector>3</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">146</distanciaTramo>
        <coordenada>
            <longitud>-0.628274</longitud>
            <latitud>39.488013</latitud>
            <altitud>149</altitud>
        </coordenada>
        <numeroSector>3</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">158</distanciaTramo>
        <coordenada>
            <longitud>-0.627150</longitud>
            <latitud>39.486864</latitud>
            <altitud>147</altitud>
        </coordenada>
        <numeroSector>3</numeroSector>
    </puntoTramo>
    <!-- Sector 4 -->
    <puntoTramo>
        <distanciaTramo unidades="metros">24</distanciaTramo>
        <coordenada>
            <longitud>-0.627195</longitud>
            <latitud>39.486647</latitud>
            <altitud>146</altitud>
        </coordenada>
        <numeroSector>4</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">130</distanciaTramo>
        <coordenada>
            <longitud>-0.628474</longitud>
            <latitud>39.486023</latitud>
            <altitud>147</altitud>
        </coordenada>
        <numeroSector>4</numeroSector>
    </puntoTramo>
    <!-- Sector 5 -->
    <puntoTramo>
        <distanciaTramo unidades="metros">33</distanciaTramo>
        <coordenada>
            <longitud>-0.628867</longitud>
            <latitud>39.486097</latitud>
            <altitud>148</altitud>
        </coordenada>
        <numeroSector>5</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">44</distanciaTramo>
        <coordenada>
            <longitud>-0.629103</longitud>
            <latitud>39.486441</latitud>
            <altitud>149</altitud>
        </coordenada>
        <numeroSector>5</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">212</distanciaTramo>
        <coordenada>
            <longitud>-0.629160</longitud>
            <latitud>39.488356</latitud>
            <altitud>154</altitud>
        </coordenada>
        <numeroSector>5</numeroSector>
    </puntoTramo>
    <!-- Sector 6 -->
    <puntoTramo>
        <distanciaTramo unidades="metros">28</distanciaTramo>
        <coordenada>
            <longitud>-0.629412</longitud>
            <latitud>39.488533</latitud>
            <altitud>155</altitud>
        </coordenada>
        <numeroSector>6</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">33</distanciaTramo>
        <coordenada>
            <longitud>-0.629791</longitud>
            <latitud>39.488493</latitud>
            <altitud>155</altitud>
        </coordenada>
        <numeroSector>6</numeroSector>
    </puntoTramo>
    <!-- Sector 7 -->
    <puntoTramo>
        <distanciaTramo unidades="metros">310</distanciaTramo>
        <coordenada>
            <longitud>-0.632738</longitud>
            <latitud>39.486880</latitud>
            <altitud>161</altitud>
        </coordenada>
        <numeroSector>7</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">161</distanciaTramo>
        <coordenada>
            <longitud>-0.633673</longitud>
            <latitud>39.485623</latitud>
            <altitud>163</altitud>
        </coordenada>
        <numeroSector>7</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">30</distanciaTramo>
        <coordenada>
            <longitud>-0.633657</longitud>
            <latitud>39.485340</latitud>
            <altitud>161</altitud>
        </coordenada>
        <numeroSector>7</numeroSector>
    </puntoTramo>
    <!-- Sector 8 -->
    <puntoTramo>
        <distanciaTramo unidades="metros">32</distanciaTramo>
        <coordenada>
            <longitud>-0.633400</longitud>
            <latitud>39.485117</latitud>
            <altitud>159</altitud>
        </coordenada>
        <numeroSector>8</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">45</distanciaTramo>
        <coordenada>
            <longitud>-0.632877</longitud>
            <latitud>39.485076</latitud>
            <altitud>158</altitud>
        </coordenada>
        <numeroSector>8</numeroSector>
    </puntoTramo>
    <!-- Sector 9 -->
    <puntoTramo>
        <distanciaTramo unidades="metros">135</distanciaTramo>
        <coordenada>
            <longitud>-0.631614</longitud>
            <latitud>39.485814</latitud>
            <altitud>156</altitud>
        </coordenada>
        <numeroSector>9</numeroSector>
    </puntoTramo>
    <!-- Sector 10 -->
    <puntoTramo>
        <distanciaTramo unidades="metros">114</distanciaTramo>
        <coordenada>
            <longitud>-0.631300</longitud>
            <latitud>39.486806</latitud>
            <altitud>155</altitud>
        </coordenada>
        <numeroSector>10</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">100</distanciaTramo>
        <coordenada>
            <longitud>-0.630377</longitud>
            <latitud>39.487331</latitud>
            <altitud>155</altitud>
        </coordenada>
        <numeroSector>10</numeroSector>
    </puntoTramo>
    <!-- Sector 11 -->
    <puntoTramo>
        <distanciaTramo unidades="metros">30</distanciaTramo>
        <coordenada>
            <longitud>-0.630051</longitud>
            <latitud>39.487273</latitud>
            <altitud>155</altitud>
        </coordenada>
        <numeroSector>11</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">35</distanciaTramo>
        <coordenada>
            <longitud>-0.629920</longitud>
            <latitud>39.486935</latitud>
            <altitud>153</altitud>
        </coordenada>
        <numeroSector>11</numeroSector>
    </puntoTramo>
    <puntoTramo>
        <distanciaTramo unidades="metros">300</distanciaTramo>
        <coordenada>
            <longitud>-0.631687</longitud>
            <latitud>39.484631</latitud>
            <altitud>155</altitud>
        </coordenada>
        <numeroSector>11</numeroSector>
    </puntoTramo>
    <!-- Sector 12 -->
    <puntoTramo>
        <distanciaTramo unidades="metros">13</distanciaTramo>
        <coordenada>
            <longitud>-0.631792</longitud>
            <latitud>39.484558</latitud>
